// <auto-generated />
namespace Ecole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _006_AjoutMoyenne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_006_AjoutMoyenne));
        
        string IMigrationMetadata.Id
        {
            get { return "201601291300025_006_AjoutMoyenne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
